### ISSUE TITLE
free(): invalid size

### ISSUE THREAD

**Issue by Tryware** [grialion/rpcpp#1]
The program connects for a while then it stops.
Error:

```
Connected to Discord.
free(): invalid size
Aborted
```

I downloaded the package from AUR

**Comment by Tryware** [comment]
Oh also a small thing here, the title should be "Linux" not "LInux"
![image](https://user-images.githubusercontent.com/82564850/156061952-ce522098-8883-4d2e-8a57-11310b7e3278.png)

**Comment by grialion** [comment]
Could you please provide any other information about your system (G++ version, X version, kernel, etc.)?
It did perfectly work on every Arch based machine I tried on, which X version are you running? Maybe XWayland, I haven't tested it under Wayland yet.
Does it always throw an error when you start the app?

Thanks for your feedback, also the text is Linux ;), Discord bold font does not display it nicely 
![image](https://user-images.githubusercontent.com/48643945/156586922-b168096c-a261-4b62-a461-a550841f31bd.png) if you hover your mouse over it, it'll display the text with a thinner font.

**Comment by Tryware** [comment]
> Could you please provide any other information about your system (G++ version, X version, kernel, etc.)? It did perfectly work on every Arch based machine I tried on, which X version are you running? Maybe XWayland, I haven't tested it under Wayland yet. Does it always throw an error when you start the app?
> 
> Thanks for your feedback, also the text is Linux ;), Discord bold font does not display it nicely ![image](https://user-images.githubusercontent.com/48643945/156586922-b168096c-a261-4b62-a461-a550841f31bd.png) if you hover your mouse over it, it'll display the text with a thinner font.

Magically, it just stopped glitching somehow. Now it works normal as expected, bizarre.
