### ISSUE TITLE
Shared libraries aren't in path

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [grialion/rpcpp#2]
```
pm  …/rpcpp/lib   main !   10:00  ./rpcpp 
./rpcpp: error while loading shared libraries: discord_game_sdk.so: cannot open shared object file: No such file or directory

pm  …/rpcpp/lib   main !   10:00  ls
discord_game_sdk.bundle  discord_game_sdk.dll  discord_game_sdk.dll.lib  discord_game_sdk.dylib  discord_game_sdk.so  rpcpp
```
Despite even running the locally build binary with the Discord SDK provided by the setup.sh script, it still is unable to find the corresponding file in the folder at root.
I also did tried first the rpcpp installed via sudo make install and executed the one locally built in the build folder.

**Comment by grialion** [comment]
Did you set up the Game SDK properly? Perhaps the libraries are missing from the lib folder.
